FROM amd64/alpine:3.21@sha256:b7adcabf8c8320af2f49b10a8ba9336f2a286d7d3f647533c638732c73e00f20 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 9502
ENTRYPOINT ["/usr/bin/hetzner_exporter"]
HEALTHCHECK CMD ["/usr/bin/hetzner_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/hetzner_exporter /usr/bin/hetzner_exporter
