# escape=`
FROM microsoft/nanoserver:10.0.14393.2430

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" `
  org.label-schema.name="Hetzner Exporter" `
  org.label-schema.vendor="Thomas Boerger" `
  org.label-schema.schema-version="1.0"

EXPOSE 9502
ENTRYPOINT ["c:\\hetzner_exporter.exe"]

COPY bin/hetzner_exporter.exe c:\hetzner_exporter.exe
