FROM amd64/alpine:3.21@sha256:9a64a732c12ebe63a5b85832ea1b032bd7c4fde32ff89af7897d3e3fc334f33e AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 9502
ENTRYPOINT ["/usr/bin/hetzner_exporter"]
HEALTHCHECK CMD ["/usr/bin/hetzner_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/hetzner_exporter /usr/bin/hetzner_exporter
