FROM arm64v8/alpine:3.18@sha256:30e6d35703c578ee703230b9dc87ada2ba958c1928615ac8a674fcbbcbb0f281 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 9502
ENTRYPOINT ["/usr/bin/hetzner_exporter"]
HEALTHCHECK CMD ["/usr/bin/hetzner_exporter", "health"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/hetzner_exporter /usr/bin/hetzner_exporter
