---
# yaml-language-server: $schema=https://www.schemastore.org/hugo.json
baseURL: https://promhippie.github.io/hetzner_exporter/
locale: en-us
title: Hetzner Exporter

params:
  author: Thomas Boerger
  description: Prometheus exporter for Hetzner
  keywords: prometheus, exporter, hetzner, robot

disableKinds:
  - rss
  - sitemap
  - taxonomy
  - term
  - section

pygmentsUseClasses: true
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

blackfriday:
  angledQuotes: true
  fractions: false
  plainIDAnchors: true
  smartlists: true
  extensions:
    - hardLineBreak

...
