---
name: docs

"on":
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v3

      - name: Setup hugo
        id: hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.98.0

      - name: Run docs
        id: docs
        run: make docs

      - name: Deploy pages
        id: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/public/

...
