---
name: kustomize

"on":
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v4

      - name: Generate manifest
        id: kustomize
        uses: actionhippie/kustomize@v2
        with:
          version: 5.2.1
          path: deploy/kubernetes/
          target: deploy/kubernetes/bundle.yml

...
